-- Flux-Change shared backend — Supabase schema (run once in SQL Editor)
-- One table holds every order from every device.

create table if not exists public.orders (
  id text primary key,               -- e.g. FC-1001 (generated by the site)
  email text not null default '',     -- buyer's sign-in email (lowercase)
  label text not null default '',     -- e.g. "Gemini AI Pro · 18 Months"
  type text not null default '',      -- Subscription | Game top-up | Game code
  price integer not null default 0,
  payment text not null default '',   -- bkash | nagad | rocket
  status text not null default 'pending',  -- pending | approved | rejected
  delivery_link text not null default '',
  player_id text not null default '',
  sender_number text not null default '',
  trx_id text not null default '',
  region text not null default '',
  platform text not null default '',
  account_info text not null default '',
  delivery_email text not null default '',
  konami_id text not null default '',
  konami_password text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists orders_email_idx on public.orders (email);
create index if not exists orders_created_idx on public.orders (created_at desc);

-- The Vercel API uses the service-role key, which bypasses RLS.
-- RLS stays ON with no public policies, so the anon key alone can do nothing.
alter table public.orders enable row level security;

-- Keep updated_at fresh on every change.
create or replace function public.touch_orders_updated_at()
returns trigger language plpgsql as $$
begin new.updated_at = now(); return new; end; $$;

drop trigger if exists orders_touch on public.orders;
create trigger orders_touch before update on public.orders
for each row execute function public.touch_orders_updated_at();
